//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rollin.Add_Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int OrderID { get; set; }
        [Required]
        [DisplayName("Customer Name")]
        public Nullable<int> CustomerID { get; set; }
        [Required]
        [DisplayName("Product Name")]
        public Nullable<int> ProductID { get; set; }
        [Required]
        //[StringLength (6, MinimumLength = 4)]
        [DisplayName("Order Number")]
        public string OrderNumber { get; set; }
        [Required]
        [DataType (DataType.Date) ]
        [DisplayName("Order Date")]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Required]
        [DisplayName("Total Amount")]
        public string TotalAmount { get; set; }
        [Required]
        [DisplayName("Customer Name")]
        public virtual Customer Customer { get; set; }
        [Required]
        [DisplayName("Product")]
        public virtual Product Product { get; set; }
    }
}
